import ttkbootstrap as ttk
from ttkbootstrap.constants import *
from ttkbootstrap.widgets.scrolled import ScrolledFrame

from guiscript import GuiScript

PRICING_METHODS = ('Fixed','Measured','Custom')

class Gui(ttk.Frame):
    def __init__(self,w):
        self.w = w
        self.screenwidth = w.winfo_screenwidth()
        self.screenheight = w.winfo_screenheight()
        self.script = GuiScript(w,self)
        super().__init__(w)

        self.nb = ttk.Notebook(master=w)
        self.nb.grid(column=0,row=0,sticky='nsew')
        self.MainFrame = ttk.Frame(master=self.nb)
        self.MainFrame.grid_columnconfigure(0,weight=1)
        self.MainFrame.grid_rowconfigure(0,weight=1)
        self.StockFrame = ttk.Frame(master=self.nb)
        self.StockFrame.grid_columnconfigure(0,weight=1)
        self.StockFrame.grid_columnconfigure(1,weight=0)
        self.StockFrame.grid_rowconfigure(0,weight=0)
        self.StockFrame.grid_rowconfigure(1,weight=1)
        self.SaleHFrame = ttk.Frame(master=self.nb)
        self.SaleHFrame.grid_columnconfigure(0,weight=1)
        self.SaleHFrame.grid_columnconfigure(1,weight=0)
        self.SaleHFrame.grid_rowconfigure(0,weight=0)
        self.SaleHFrame.grid_rowconfigure(1,weight=1)
        self.SettingsFrame = ttk.Frame(master=self.nb)
        self.SettingsFrame.grid_columnconfigure(0,weight=1)
        self.SettingsFrame.grid_rowconfigure(0,weight=1)

        self.nb.add(self.MainFrame,text='Main')
        self.nb.add(self.StockFrame,text='Stock')
        self.nb.add(self.SaleHFrame,text='Sale History')
        self.nb.add(self.SettingsFrame,text='Settings')
        self.nb.bind("<<NotebookTabChanged>>", self.script.NotebookTabChange)

        # STOCK
        self.StockSearchBar = ttk.Entry(master=self.StockFrame)
        self.StockSearchBar.grid(column=0,row=0,sticky='ew')
        self.StockList = ttk.Treeview(master=self.StockFrame,columns=('Name','Quantity','Buy Cost','Sale Price'))
        self.StockList.grid(column=0,row=1,sticky='nsew')
        self.StockList.column('#0',anchor='center',stretch=False,width=50)
        self.StockList.heading('#0',text='No.')
        self.StockList.heading('Name',text='Name')
        self.StockList.column('Quantity',anchor='center')
        self.StockList.heading('Quantity',text='Quantity')
        self.StockList.column('Buy Cost',anchor='center')
        self.StockList.heading('Buy Cost',text='Buy Cost')
        self.StockList.column('Sale Price',anchor='center')
        self.StockList.heading('Sale Price',text='Sale Price')
        self.StockScroll = ttk.Scrollbar(master=self.StockFrame,orient=VERTICAL,command=self.StockList.yview,bootstyle="primary-round")
        self.StockList.configure(yscrollcommand=self.StockScroll.set)
        self.StockScroll.grid(column=1,row=1,sticky='ns')
        self.Stock_NewButton = ttk.Button(master=self.StockFrame,bootstyle="outline",text='New Stock',width=25,command=self.script.NewStockGui)
        self.Stock_NewButton.grid(column=0,row=2,pady=2)
        self.Stock_UpdateButton = ttk.Button(master=self.StockFrame,bootstyle="outline",text='Preview/Update Stock',width=25,command=self.script.UpdateStockGui)
        self.Stock_UpdateButton.grid(column=0,row=3,pady=2)

        # SALE
        self.SaleSearchBar = ttk.Entry(master=self.SaleHFrame)
        self.SaleSearchBar.grid(column=0,row=0,sticky='ew')
        self.SaleList = ttk.Treeview(master=self.SaleHFrame,columns=('Date','Items','Total','Profit'))
        self.SaleList.grid(column=0,row=1,sticky='nsew')
        self.SaleList.column('#0',anchor='center',stretch=False,width=50)
        self.SaleList.heading('#0',text='No.')
        self.SaleList.heading('Date',text='Date')
        self.SaleList.heading('Items',text='Items')
        self.SaleList.column('Total',anchor='center')
        self.SaleList.heading('Total',text='Total Price')
        self.SaleList.column('Profit',anchor='center')
        self.SaleList.heading('Profit',text='Profit')
        self.SaleScroll = ttk.Scrollbar(master=self.SaleHFrame,orient=VERTICAL,command=self.SaleList.yview,bootstyle="primary-round")
        self.SaleList.configure(yscrollcommand=self.SaleScroll.set)
        self.SaleScroll.grid(column=1,row=1,sticky='ns')
        self.ProfitTotalText = ttk.Label(master=self.SaleHFrame,text='Total Profit: 0',anchor='e')
        self.ProfitTotalText.grid(column=0,row=2,sticky='e')
        self.Sale_NewButton = ttk.Button(master=self.SaleHFrame,bootstyle="outline",text='New Sale History',width=25,command=self.script.NewSaleHGui)
        self.Sale_NewButton.grid(column=0,row=2,pady=2)
        self.Sale_UpdateButton = ttk.Button(master=self.SaleHFrame,bootstyle="outline",text='Preview/Update History',width=25,command=self.script.UpdateSaleGui)
        self.Sale_UpdateButton.grid(column=0,row=3,pady=2)

        # MAIN
        self.MainSubFrame = ScrolledFrame(master=self.MainFrame)
        self.MainSubFrame.grid(column=0,row=0,sticky='nsew')
        self.MainSubFrame.grid_columnconfigure(0,weight=1)
        self.AvgCustomers = ttk.Label(master=self.MainSubFrame,text='Average customers: 0/day')
        self.AvgCustomers.grid(column=0,row=0,sticky='w')
        self.AvgProfit = ttk.Label(master=self.MainSubFrame,text='Average profit: 0/day')
        self.AvgProfit.grid(column=0,row=1,sticky='w')
        self.AvgItemsSold = ttk.Label(master=self.MainSubFrame,text='Average items sold: 0/day')
        self.AvgItemsSold.grid(column=0,row=2,sticky='w')

        # SETTINGS
        self.SettingsSubFrame = ScrolledFrame(master=self.SettingsFrame)
        self.SettingsSubFrame.grid(column=0,row=0,sticky='nsew')
        self.SettingsSubFrame.grid_columnconfigure(0,weight=1)
        self.FileSect_Title = ttk.Label(master=self.SettingsSubFrame,text='File',bootstyle='info')
        self.FileSect_Title.grid(column=0,row=0,sticky='ew',padx=5,pady=10)
        self.FileSect = ttk.Separator(master=self.SettingsSubFrame,bootstyle='primary')
        self.FileSect.grid(column=0,row=1,sticky='ew')
        self.FileSectFrame = ttk.Frame(master=self.SettingsSubFrame)
        self.FileSectFrame.grid(column=0,row=2,sticky='ew')
        self.SelectedFileTitle = ttk.Label(master=self.FileSectFrame,text='Selected File:')
        self.SelectedFileTitle.grid(column=0,row=0,sticky='w',padx=(10,5),pady=5)
        self.OpenFileButton = ttk.Button(master=self.FileSectFrame,text='Open...',width=10,command=self.script.OpenFile)
        self.OpenFileButton.grid(column=1,row=0,padx=5,pady=5)
        self.SelectedFileInfo = ttk.Label(master=self.FileSectFrame,text='None, Click Save As to create new one')
        self.SelectedFileInfo.grid(column=2,row=0,padx=5,pady=5)
        self.SaveButton = ttk.Button(master=self.FileSectFrame,text='Save',bootstyle='default-outline',width=10,command=self.script.Save)
        self.SaveButton.grid(column=0,row=1,padx=(10,5),pady=5)
        self.SaveAsButton = ttk.Button(master=self.FileSectFrame,text='Save As',bootstyle='default-outline',width=10,command=self.script.NewSave)
        self.SaveAsButton.grid(column=1,row=1,padx=5,pady=5)

        self.StatSect_Title = ttk.Label(master=self.SettingsSubFrame,text='Statistics',bootstyle='info')
        self.StatSect_Title.grid(column=0,row=3,sticky='ew',padx=5,pady=10)
        self.FileSect = ttk.Separator(master=self.SettingsSubFrame,bootstyle='primary')
        self.FileSect.grid(column=0,row=4,sticky='ew')
        self.StatSectFrame = ttk.Frame(master=self.SettingsSubFrame)
        self.StatSectFrame.grid(column=0,row=5,sticky='ew')
        self.OperatingDaysTitle = ttk.Label(master=self.StatSectFrame,text='Operating days per week: 1')
        self.OperatingDaysTitle.grid(column=0,row=6,sticky='w',padx=(10,5),pady=5)
        self.OperatingDaysInput = ttk.Scale(master=self.StatSectFrame,from_=1,to=7,command=self.script.SettingsOperatingDaysScale)
        self.OperatingDaysInput.grid(column=0,row=7,sticky='ew',padx=(10,5),pady=5)

        self.script.UpdateDataGui()
    def NewStockGui(self):
        width, height = 800, 450
        xcenter = (self.screenwidth // 2) - (width // 2)
        ycenter = (self.screenheight // 2) - (height // 2)

        self.NewStockWindow = ttk.Toplevel(title='New Stock')
        self.NewStockWindow.iconbitmap('Icon.ico')
        self.NewStockWindow.geometry(f'{width}x{height}+{xcenter}+{ycenter}')
        self.NewStockWindow.resizable(False,False)
        
        self.NameInpText = ttk.Label(master=self.NewStockWindow,text='Name')
        self.NameInpText.grid(column=0,row=0,sticky='w',padx=15,pady=(15,2))
        self.NameInput = ttk.Entry(master=self.NewStockWindow,width=65)
        self.NameInput.grid(column=1,row=0,sticky='w',pady=(15,2))

        self.QuantityInpText = ttk.Label(master=self.NewStockWindow,text='Quantity')
        self.QuantityInpText.grid(column=0,row=1,sticky='w',padx=15,pady=2)
        self.QuantityInput = ttk.Entry(master=self.NewStockWindow)
        self.QuantityInput.grid(column=1,row=1,sticky='w',pady=2)

        self.PMethodText = ttk.Label(master=self.NewStockWindow,text='Pricing Method')
        self.PMethodText.grid(column=0,row=2,sticky='w',padx=15,pady=2)
        self.PricingMethod = ttk.Combobox(master=self.NewStockWindow,state='readonly',values=PRICING_METHODS)
        self.PricingMethod.grid(column=1,row=2,sticky='w',pady=2)
        self.PricingMethod.current(0)
        self.PricingMethod.bind("<<ComboboxSelected>>", self.script.StockPricingMethodSelect)

        self.MeasurementInpText = ttk.Label(master=self.NewStockWindow,text='Measurement (e.g. kg, liter)')
        self.MeasurementInput = ttk.Entry(master=self.NewStockWindow)

        self.BuyInpText = ttk.Label(master=self.NewStockWindow,text='Buy Cost')
        self.BuyInpText.grid(column=0,row=4,sticky='w',padx=15,pady=2)
        self.BuyInput = ttk.Entry(master=self.NewStockWindow)
        self.BuyInput.grid(column=1,row=4,sticky='w',pady=2)

        self.SaleInpText = ttk.Label(master=self.NewStockWindow,text='Sale Price')
        self.SaleInpText.grid(column=0,row=5,sticky='w',padx=15,pady=2)
        self.SaleInput = ttk.Entry(master=self.NewStockWindow)
        self.SaleInput.grid(column=1,row=5,sticky='w',pady=2)

        self.StockDateText = ttk.Label(master=self.NewStockWindow,text='Stock Date')
        self.StockDateText.grid(column=0,row=6,sticky='w',padx=15,pady=2)
        self.StockDateInput = ttk.DateEntry(master=self.NewStockWindow,dateformat="%d/%m/%Y")
        self.StockDateInput.grid(column=1,row=6,sticky='w',pady=2)

        self.NoteInpText = ttk.Label(master=self.NewStockWindow,text='Note')
        self.NoteInpText.grid(column=0,row=7,sticky='w',padx=15,pady=2)
        self.NoteInput = ttk.Entry(master=self.NewStockWindow,width=65)
        self.NoteInput.grid(column=1,row=7,sticky='w',pady=2)

        self.AddButton = ttk.Button(master=self.NewStockWindow,text='Add Stock',bootstyle='success',width=15,command=self.script.DoAddStock)
        self.AddButton.grid(column=1,row=8,pady=(12,2))
        self.CancelButton = ttk.Button(master=self.NewStockWindow,text='Cancel',bootstyle='danger',width=15,command=self.NewStockWindow.destroy)
        self.CancelButton.grid(column=1,row=9,pady=2)

        self.w.wait_window(self.NewStockWindow)
        self.w.deiconify()
    def UpdateStockGui(self):
        width, height = 800, 400
        xcenter = (self.screenwidth // 2) - (width // 2)
        ycenter = (self.screenheight // 2) - (height // 2)

        self.UpdStockWindow = ttk.Toplevel(title='Preview Stock')
        self.UpdStockWindow.iconbitmap('Icon.ico')
        self.UpdStockWindow.geometry(f'{width}x{height}+{xcenter}+{ycenter}')
        self.UpdStockWindow.resizable(False,False)

        self.NameInpText = ttk.Label(master=self.UpdStockWindow,text='Name')
        self.NameInpText.grid(column=0,row=0,sticky='w',padx=15,pady=(15,2))
        self.NameInput = ttk.Entry(master=self.UpdStockWindow,width=65)
        self.NameInput.grid(column=1,row=0,sticky='w',pady=(15,2))

        self.QuantityInpText = ttk.Label(master=self.UpdStockWindow,text='Quantity')
        self.QuantityInpText.grid(column=0,row=1,sticky='w',padx=15,pady=2)
        self.QuantityInput = ttk.Entry(master=self.UpdStockWindow)
        self.QuantityInput.grid(column=1,row=1,sticky='w',pady=(2,0))

        self.AddQuantityInpText = ttk.Label(master=self.UpdStockWindow,text='Additional Quantity',bootstyle='primary')
        self.AddQuantityInpText.grid(column=0,row=2,sticky='w',padx=15,pady=2)
        self.AddQuantityInput = ttk.Entry(master=self.UpdStockWindow,bootstyle='primary')
        self.AddQuantityInput.grid(column=1,row=2,sticky='w',pady=(1,3))
        self.AddQuantityInput.insert(0,'0')

        self.BuyInpText = ttk.Label(master=self.UpdStockWindow,text='Buy Cost')
        self.BuyInpText.grid(column=0,row=3,sticky='w',padx=15,pady=2)
        self.BuyInput = ttk.Entry(master=self.UpdStockWindow)
        self.BuyInput.grid(column=1,row=3,sticky='w',pady=2)

        self.SaleInpText = ttk.Label(master=self.UpdStockWindow,text='Sale Price')
        self.SaleInpText.grid(column=0,row=4,sticky='w',padx=15,pady=2)
        self.SaleInput = ttk.Entry(master=self.UpdStockWindow)
        self.SaleInput.grid(column=1,row=4,sticky='w',pady=2)

        self.NoteInpText = ttk.Label(master=self.UpdStockWindow,text='Note')
        self.NoteInpText.grid(column=0,row=5,sticky='w',padx=15,pady=2)
        self.NoteInput = ttk.Entry(master=self.UpdStockWindow,width=65)
        self.NoteInput.grid(column=1,row=5,sticky='w',pady=2)

        # self.HistoryButton = ttk.Button(master=self.UpdStockWindow,text='History',bootstyle='primary-outline',width=13,command=self.StockHistoryGui)
        # self.HistoryButton.grid(column=0,row=6,pady=(12,2))

        self.UpdButton = ttk.Button(master=self.UpdStockWindow,text='Update Stock',bootstyle='success',width=15,command=self.script.DoUpdStock)
        self.UpdButton.grid(column=1,row=6,pady=(12,2))
        self.CancelButton = ttk.Button(master=self.UpdStockWindow,text='Cancel',bootstyle='danger',width=15,command=self.UpdStockWindow.destroy)
        self.CancelButton.grid(column=1,row=7,pady=2)
        self.DeleteButton = ttk.Button(master=self.UpdStockWindow,text='Delete Stock',bootstyle='danger-outline',width=15,command=self.script.DeleteStock)
        self.DeleteButton.grid(column=1,row=8,pady=2)

        self.script.UpdateDataInUpdStockGui()
        self.w.wait_window(self.UpdStockWindow)
        self.w.deiconify()
    def NewSaleHGui(self):
        width, height = 850, 450
        xcenter = (self.screenwidth // 2) - (width // 2)
        ycenter = (self.screenheight // 2) - (height // 2)

        self.NewSaleHWindow = ttk.Toplevel(title='New Sale History')
        self.NewSaleHWindow.iconbitmap('Icon.ico')
        self.NewSaleHWindow.geometry(f'{width}x{height}+{xcenter}+{ycenter}')
        self.NewSaleHWindow.resizable(False,False)
        self.NewSaleHWindow.grid_columnconfigure(0,weight=1)

        self.ItemList = ttk.Treeview(master=self.NewSaleHWindow,columns=('Name','Quantity','Total Price'))
        self.ItemList.grid(column=0,row=0,sticky='nsew',padx=(10,0),pady=(10,20))
        self.ItemList.column('#0',anchor='center',stretch=False,width=40)
        self.ItemList.heading('#0',text='No.')
        self.ItemList.heading('Name',text='Name')
        self.ItemList.column('Quantity',anchor='center',stretch=False,width=75)
        self.ItemList.heading('Quantity',text='Quantity')
        self.ItemList.column('Total Price',anchor='center',width=85)
        self.ItemList.heading('Total Price',text='Total Price')
        self.ItemScroll = ttk.Scrollbar(master=self.NewSaleHWindow,orient=VERTICAL,command=self.ItemList.yview,bootstyle="primary-round")
        self.ItemList.configure(yscrollcommand=self.ItemScroll.set)
        self.ItemScroll.grid(column=1,row=0,sticky='ns')

        self.ItemInpText = ttk.Label(master=self.NewSaleHWindow,text='Item')
        self.ItemInpText.grid(column=2,row=0,sticky='ew',padx=15)
        self.ItemInput = ttk.Combobox(master=self.NewSaleHWindow)
        self.ItemInput.grid(column=3,row=0,padx=(10,2),sticky='ew')
        self.ItemInput.bind("<<ComboboxSelected>>", self.script.ItemSaleSelect)
        self.ItemQuantity = ttk.Entry(master=self.NewSaleHWindow,width=6)
        self.ItemQuantity.grid(column=4,row=0,padx=(0,10),sticky='ew')

        self.ItemPriceText = ttk.Label(master=self.NewSaleHWindow,text='Please select an item.',font=('Arial',6),anchor=N)
        self.ItemPriceText.grid(column=3,row=0,pady=(65,0))

        self.AddItemButton = ttk.Button(master=self.NewSaleHWindow,text='Add Item',width=15,bootstyle='prime-outline',command=self.script.DoAddSaleItem)
        self.AddItemButton.grid(column=3,row=0,pady=(140,0))
        self.RemoveItemButton = ttk.Button(master=self.NewSaleHWindow,text='Remove Selected',width=15,bootstyle='danger-outline',command=self.script.DoDeleteSaleItem)
        self.RemoveItemButton.grid(column=3,row=0,pady=(220,0))

        self.DateInpText = ttk.Label(master=self.NewSaleHWindow,text='Date')
        self.DateInpText.grid(column=0,row=1,sticky='w',padx=15,pady=2)
        self.DateInput = ttk.DateEntry(master=self.NewSaleHWindow,width=40,dateformat="%d/%m/%Y")
        self.DateInput.grid(column=0,row=1,sticky='e',pady=2)

        self.NoteInpText = ttk.Label(master=self.NewSaleHWindow,text='Note')
        self.NoteInpText.grid(column=0,row=2,sticky='w',padx=15,pady=2)
        self.NoteInput = ttk.Entry(master=self.NewSaleHWindow,width=46)
        self.NoteInput.grid(column=0,row=2,sticky='e',pady=2)

        self.AddSaleButton = ttk.Button(master=self.NewSaleHWindow,text='Add Sale',bootstyle='success',width=15,command=self.script.DoAddSaleHistory)
        self.AddSaleButton.grid(column=0,row=3,padx=25,pady=(10,5))
        self.CancelButton = ttk.Button(master=self.NewSaleHWindow,text='Cancel',bootstyle='danger',width=15,command=self.NewSaleHWindow.destroy)
        self.CancelButton.grid(column=0,row=4,padx=25,pady=5)

        self.script.UpdateDataInNewSaleGui()
        self.w.wait_window(self.NewSaleHWindow)
        self.w.deiconify()
    def CustomPriceGui(self):
        width, height = 300, 200
        xcenter = (self.screenwidth // 2) - (width // 2)
        ycenter = (self.screenheight // 2) - (height // 2)
        PriceSet = ttk.BooleanVar(value=False)
        InputVar = ttk.StringVar()

        self.CustomPriceWindow = ttk.Toplevel(title='Custom Price')
        self.CustomPriceWindow.iconbitmap('Icon.ico')
        self.CustomPriceWindow.geometry(f'{width}x{height}+{xcenter}+{ycenter}')
        self.CustomPriceWindow.resizable(False,False)
        self.CustomPriceWindow.grab_set()
        self.CustomPriceWindow.grid_columnconfigure(0,weight=1)
        
        self.Txt = ttk.Label(master=self.CustomPriceWindow,text='Custom Price',anchor=CENTER)
        self.Txt.grid(column=0,row=0,padx=15,pady=(15,2),sticky='ew')
        self.CustomPriceInput = ttk.Entry(master=self.CustomPriceWindow,width=25,textvariable=InputVar)
        self.CustomPriceInput.grid(column=0,row=1,pady=2)

        self.ApplyButton = ttk.Button(master=self.CustomPriceWindow,width=15,text='Apply',bootstyle='primary-outline',command=lambda:(PriceSet.set(True),self.CustomPriceWindow.destroy()))
        self.ApplyButton.grid(column=0,row=2,pady=(10,5))
        self.CancelButton = ttk.Button(master=self.CustomPriceWindow,width=15,text='Cancel',bootstyle='danger-outline',command=self.CustomPriceWindow.destroy)
        self.CancelButton.grid(column=0,row=3,pady=(5,15))

        self.w.wait_window(self.CustomPriceWindow)
        self.CustomPriceWindow.grab_release()
        return (PriceSet.get(), InputVar.get())
    def UpdateSaleGui(self):
        width, height = 850, 500
        xcenter = (self.screenwidth // 2) - (width // 2)
        ycenter = (self.screenheight // 2) - (height // 2)

        self.UpdSaleWindow = ttk.Toplevel(title='Preview Sale History')
        self.UpdSaleWindow.iconbitmap('Icon.ico')
        self.UpdSaleWindow.geometry(f'{width}x{height}+{xcenter}+{ycenter}')
        self.UpdSaleWindow.resizable(False,False)
        self.UpdSaleWindow.grid_columnconfigure(0,weight=1)

        self.ItemList = ttk.Treeview(master=self.UpdSaleWindow,columns=('Name','Quantity','Total Price'))
        self.ItemList.grid(column=0,row=0,sticky='nsew',padx=(10,0),pady=(10,20))
        self.ItemList.column('#0',anchor='center',stretch=False,width=40)
        self.ItemList.heading('#0',text='No.')
        self.ItemList.heading('Name',text='Name')
        self.ItemList.column('Quantity',anchor='center',stretch=False,width=75)
        self.ItemList.heading('Quantity',text='Quantity')
        self.ItemList.column('Total Price',anchor='center',width=85)
        self.ItemList.heading('Total Price',text='Total Price')
        self.ItemScroll = ttk.Scrollbar(master=self.UpdSaleWindow,orient=VERTICAL,command=self.ItemList.yview,bootstyle="primary-round")
        self.ItemList.configure(yscrollcommand=self.ItemScroll.set)
        self.ItemScroll.grid(column=1,row=0,sticky='ns')

        self.DateInpText = ttk.Label(master=self.UpdSaleWindow,text='Date')
        self.DateInpText.grid(column=0,row=1,sticky='w',padx=15,pady=2)
        self.DateInput = ttk.DateEntry(master=self.UpdSaleWindow,width=25,dateformat="%d/%m/%Y")
        self.DateInput.grid(column=0,row=1,sticky='w',padx=(75,0),pady=2)

        self.NoteInpText = ttk.Label(master=self.UpdSaleWindow,text='Note')
        self.NoteInpText.grid(column=0,row=2,sticky='w',padx=15,pady=2)
        self.NoteInput = ttk.Entry(master=self.UpdSaleWindow,width=75)
        self.NoteInput.grid(column=0,row=2,sticky='w',padx=(75,0),pady=2)

        self.SaveButton = ttk.Button(master=self.UpdSaleWindow,text='Save',bootstyle='success',width=15,command=self.script.DoUpdSaleHistory)
        self.SaveButton.grid(column=0,row=3,padx=25,pady=(10,5))
        self.CancelButton = ttk.Button(master=self.UpdSaleWindow,text='Cancel',bootstyle='danger',width=15,command=self.UpdSaleWindow.destroy)
        self.CancelButton.grid(column=0,row=4,padx=25,pady=5)
        self.DeleteButton = ttk.Button(master=self.UpdSaleWindow,text='Delete History',bootstyle='danger-outline',width=15,command=self.script.DoDeleteSaleHistory)
        self.DeleteButton.grid(column=0,row=5,padx=25,pady=5)

        self.script.UpdateDataInUpdSaleGui()
        self.w.wait_window(self.UpdSaleWindow)
        self.w.deiconify()
